### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by kbruegge** [fact-project/fact_plots#2]
After installing with
```
pip install git+https://github.com/fact-project/fact_plots.git
```
I get the following stacktrace.

```
→ fact_plot_theta --help
Traceback (most recent call last):
  File "/Users/mackaiver/.anaconda3/bin/fact_plot_theta", line 9, in <module>
    load_entry_point('fact-plots==0.0.1', 'console_scripts', 'fact_plot_theta')()
  File "/Users/mackaiver/.anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "/Users/mackaiver/.anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "/Users/mackaiver/.anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2229, in load
  File "/Users/mackaiver/.anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/Users/mackaiver/.anaconda3/lib/python3.5/site-packages/fact_plots/scripts/plot_theta.py", line 24, in <module>
    from fact_plots.utils import li_ma_significance, theta_mm_to_theta_squared_deg
ImportError: cannot import name 'li_ma_significance'
```

I guess the li_ma function can be replaced by the one in pyfact in any case.

**Comment by kbruegge** [comment]
This was solved at some point.
